baseURL: https://hm37.net
languageCode: en-us
defaultContentLanguage: en
title: hm37
theme: ["hugo-video", "cupper-hugo-theme"]
googleAnalytics: UA-36664418-3
disqusShortname: hm37
enableGitInfo: true

taxonomies:
  tag: tags

permalinks:
  guides: /guide/:slug
  playing: /playing/:slug
  coffees: /coffee/:slug
  software: /software/:slug

imaging:
  quality: 99

params:
  description: Thoughts, stories, and technical articles.
  homeMetaContent: Tom's Thoughts. Another weblog for your reading pleasure.
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to [Netlify](https://www.netlify.com/). Source Code on [GitHub](https://github.com/hackerman1337-xo/hm37.net)
  dateFormat: 2006 Jan 02
  codePenUser: neontom
  katex: false
  darkThemeAsDefault: false
  hideHeaderLinks: false
  search: true

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Guides
      url: /guides/
      weight: 2
    - name: Software
      url: /software/
      weight: 3
    - name: Currently Playing
      url: /playing/
      weight: 4
    - name: Tags
      url: /tags/
      weight: 5
    - name: Security
      url: /security/
      weight: 6
    - name: About
      url: /about/
      weight: 7
    - name: RSS
      url: /index.xml
      weight: 8

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
